services:
  - type: web
    name: octave-api
    env: python
    runtime: python-3.11.10
    rootDir: backend
    buildCommand: "pip install --upgrade pip setuptools wheel && pip install -r requirements-simple.txt"
    startCommand: "uvicorn test_simple:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PORT
        value: 10000
      - key: ENV
        value: prod
      - key: DEBUG
        value: false
      - key: API_RELOAD
        value: false 